modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0"

[[mods]]
    modId="create_commerce"
    version="0.1.0"
    displayName="Create: Commerce"
    description='''
        A Create add-on that adds commerce systems to villages.
    '''

[[dependencies.create_commerce]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.187,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_commerce]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_commerce]]
    modId="create"
    type="required"
    versionRange="[6.0.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_commerce]]
    modId        = "numismatics"
    type         = "required"
    versionRange = "[1.0.18,)"
    ordering     = "AFTER"
    side         = "BOTH"
